server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此次配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                passowrd: guest
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名字
          destrination: studyExchange #表示要使用Exchange名称定义
          content-type: application/json #设置消息类型，本次为json，文本为‘text/plain’
          binder: defaultRabbit #是在要绑定的消息服务具体设置
          group: a #分组 避免多个微服务重复消费

eureka:
  instance:
    instance-id: receive-8802.com #在信息列表显示主机名称
    prefer-ip-address: true #访问路径变为ip地址
    #Eureka客户端向服务端发送心跳的时间间隔，单位秒（默认30秒）
    lease-renewal-interval-in-seconds: 2
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位秒（默认90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
