server:
  port: 8001
eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false 表示自己是注册中心，不需要检索服务
    fetch-registry: true
    service-url:
    #设置与Eureka Server 交互的地址查询服务和组成服务都要依赖这个地址
     defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-provider-hystrix-payment